apiVersion: apps/v1
kind: Deployment

metadata:
  name: feedbackapp-deploy
  namespace: {{ .Values.namespace.name }}
  labels:
    app: feedbackApp
    managed-by: Helm
    version: v1

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: feedbackApp

  template:
    metadata:
      labels:
        app: feedbackApp

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "manofer/feedbackapp:0.2"        # "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9090
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb-0.mongodb.default.svc.cluster.local:27017"
