apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}

spec:
  selector:
    app: feedbackApp
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

